// Exportar todos los tipos desde types
export * from '../types'

// Exportar todos los servicios
export { usuarioService } from './UsuarioService'
export { estudianteService } from './EstudianteService'
export { docenteService } from './DocenteService'
export { administradorService } from './AdministradorService'
export { facultadService } from './FacultadService'
export { edificioService } from './EdificioService'
export { pisoService } from './PisoService'
export { aulaService } from './AulaService'
export { materiaService } from './MateriaService'
export { paraleloService } from './ParaleloService'
export { horarioService } from './HorarioService'
export { matriculaService } from './MatriculaService'

// Exportar tipos de creación
export type { CreateUsuario } from './UsuarioService'
export type { CreateEstudiante } from './EstudianteService'
export type { CreateDocente } from './DocenteService'
export type { CreateAdministrador } from './AdministradorService'
export type { CreateFacultad } from './FacultadService'
export type { CreateEdificio } from './EdificioService'
export type { CreatePiso } from './PisoService'
export type { CreateAula } from './AulaService'
export type { CreateMateria } from './MateriaService'
export type { CreateParalelo } from './ParaleloService'
export type { CreateHorario } from './HorarioService'
export type { CreateMatricula } from './MatriculaService'
